theme: jekyll-theme-minimal
title: Nuclear Miner
description: Safe and Efficient Bitcoin Miner
logo: https://github.com/nuclearminerdotcom/nuclearminerdotcom.github.io/blob/main/img/logo-600.png?raw=true
show_downloads: false
